version: '3.9'
services:
  api_client:
    build: .
    volumes:
      - .:/usr/src/app
      - ./vendor/bundle:/app/vendor/bundle
    env_file:
      - .env
    environment:
      BUNDLE_PATH: /app/vendor/bundle
      GEM_HOME: /app/vendor/bundle/ruby/3.4.3
